module.exports = {
	"useTabs": true,
	"semi": true,
	"singleQuote": true,
	"quoteProps": "consistent",
	"jsxSingleQuote": true,
	"trailingComma": "es5",
	"bracketSpacing": true,
	"jsxBracketSameLine": true,
	"arrowParens": "always",
	"requirePragma": false,
	"insertPragma": false,
	"proseWrap": "preserve",
	"htmlWhitespaceSensitivity": "css",
	"endOfLine": "lf",
};
